const carData = [
  {
    "id": 1,
    "type": "Car",
    "make": "Ford",
    "model": "Focus",
    "colour": "Dark Grey",
    "engine": 1.9,
    "engineType": "Diesel",
    "mileage": 41253,
    "transmission": "Manual",
    "modCons": {
      "airCon": true,
      "cdMp3": true,
      "cruise": true,
      "electricWindows": true, 
      "electricMirrors": true,
      "heatedMirrors": false,
      "heatedSeats": false,
      "heatedWindscreen": true,
      "PAS": true,
      "parkingSensors": true,
      "reverseCameraAssist": false,
      "GPS": true
    },
    "year": 2015,
    "serviceHistory": "Part",
    "price": 12995,
    "images": {
      "image1": "src/assets/car-listings/ford/focus/2015/dark-grey/focus_1.jpg",
      "image2": "src/assets/car-listings/ford/focus/2015/dark-grey/focus_2.jpg",
      "image3": "src/assets/car-listings/ford/focus/2015/dark-grey/focus_3.jpg",
      "image4": "src/assets/car-listings/ford/focus/2015/dark-grey/focus_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100001"
  },

  {
    "id": 2,
    "type": "Car",
    "make": "Ford",
    "model": "Mondeo",
    "colour": "Silver",
    "engine": 2.2,
    "engineType": "Petrol",
    "mileage": 32158,
    "transmission": "Manual",
    "modCons": {
      "airCon": true,
      "cdMp3": true,
      "cruise": true,
      "electricWindows": true, 
      "electricMirrors": true,
      "heatedMirrors": true,
      "heatedSeats": false,
      "heatedWindscreen": true,
      "PAS": true,
      "parkingSensors": true,
      "reverseCameraAssist": true,
      "GPS": true
    },
    "year": 2016,
    "serviceHistory": "Full (Dealer)",
    "price": 13699,
    "images": {
      "image1": "src/assets/car-listings/ford/mondeo/2016/silver/mondeo_1.jpg",
      "image2": "src/assets/car-listings/ford/mondeo/2016/silver/mondeo_2.jpg",
      "image3": "src/assets/car-listings/ford/mondeo/2016/silver/mondeo_3.jpg",
      "image4": "src/assets/car-listings/ford/mondeo/2016/silver/mondeo_1.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100002"
  },
  
  {
    "id": 3,
    "type": "Car",
    "make": "Vauxhall",
    "model": "Astra",
    "colour": "Black",
    "engine": 1.6,
    "engineType": "Petrol",
    "mileage": 64122,
    "transmission": "Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": false,
                  "cruise": false,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": false,
                  "heatedSeats": false,
                  "heatedWindscreen": false,
                  "PAS": true,
                  "parkingSensors": false,
                  "reverseCameraAssist": false,
                  "GPS": false
                },
    "year": 2008,
    "serviceHistory": "Part",
    "price": 1999,
    "images": {
      "image1": "src/assets/car-listings/vauxhall/astra/2008/black/astra_1.jpg",
      "image2": "src/assets/car-listings/vauxhall/astra/2008/black/astra_2.jpg",
      "image3": "src/assets/car-listings/vauxhall/astra/2008/black/astra_3.jpg",
      "image4": "src/assets/car-listings/vauxhall/astra/2008/black/astra_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100003"
  },

  {
    "id": 4,
    "type": "Car",
    "make": "Volkswagen",
    "model": "Golf",
    "colour": "Metallic Blue",
    "engine": 1.6,
    "engineType": "Diesel",
    "mileage": 34029,
    "transmission": "Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": false,
                  "heatedSeats": true,
                  "heatedWindscreen": false,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2013,
    "serviceHistory": "Full (Dealer)",
    "price": 9695,
    "images": {
      "image1": "src/assets/car-listings/vw/golf/2013/blue/golf_1.jpg",
      "image2": "src/assets/car-listings/vw/golf/2013/blue/golf_2.jpg",
      "image3": "src/assets/car-listings/vw/golf/2013/blue/golf_3.jpg",
      "image4": "src/assets/car-listings/vw/golf/2013/blue/golf_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100004"
  },

  {
    "id": 5,
    "type": "Car",
    "make": "Volkswagen",
    "model": "Passat",
    "colour": "Red Wine",
    "engine": 2.0,
    "engineType": "Diesel",
    "mileage": 22029,
    "transmission": "Manual",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": false,
                  "heatedSeats": true,
                  "heatedWindscreen": false,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2016,
    "serviceHistory": "Full (Dealer)",
    "price": 16195,
    "images": {
      "image1": "src/assets/car-listings/vw/passat/2016/wine/passat_1.jpg",
      "image2": "src/assets/car-listings/vw/passat/2016/wine/passat_2.jpg",
      "image3": "src/assets/car-listings/vw/passat/2016/wine/passat_3.jpg",
      "image4": "src/assets/car-listings/vw/passat/2016/wine/passat_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100005"
  },

  {
    "id": 6,
    "type": "Car",
    "make": "Seat",
    "model": "Leon FR",
    "colour": "White",
    "engine": 2.0,
    "engineType": "Diesel",
    "mileage": 12531,
    "transmission": "Manual",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": true,
                  "heatedSeats": true,
                  "heatedWindscreen": true,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2017,
    "serviceHistory": "Full (Dealer)",
    "price": 17095,
    "images": {
      "image1": "src/assets/car-listings/seat/leon/2017/white/leon_1.jpg",
      "image2": "src/assets/car-listings/seat/leon/2017/white/leon_2.jpg",
      "image3": "src/assets/car-listings/seat/leon/2017/white/leon_3.jpg",
      "image4": "src/assets/car-listings/seat/leon/2017/white/leon_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100006"
  },

  {
    "id": 7,
    "type": "Car",
    "make": "Volvo",
    "model": "V40 D4",
    "colour": "Sky Blue",
    "engine": 2.0,
    "engineType": "Diesel",
    "mileage": 54273,
    "transmission": "Semi-Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": false,
                  "heatedSeats": true,
                  "heatedWindscreen": false,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": false,
                  "GPS": false
                },
    "year": 2013,
    "serviceHistory": "Part (Dealer)",
    "price": 9299,
    "images": {
      "image1": "src/assets/car-listings/volvo/v40 d4/2013/sky blue/v40_d4_1.jpg",
      "image2": "src/assets/car-listings/volvo/v40 d4/2013/sky blue/v40_d4_2.jpg",
      "image3": "src/assets/car-listings/volvo/v40 d4/2013/sky blue/v40_d4_3.jpg",
      "image4": "src/assets/car-listings/volvo/v40 d4/2013/sky blue/v40_d4_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100007"
  },

  {
    "id": 8,
    "type": "Car",
    "make": "BMW",
    "model": "X5",
    "colour": "Black",
    "engine": 4.4,
    "engineType": "Petrol",
    "mileage": 34904,
    "transmission": "Semi-Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": true,
                  "heatedSeats": true,
                  "heatedWindscreen": true,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2016,
    "serviceHistory": "Part (Dealer)",
    "price": 22998,
    "images": {
      "image1": "src/assets/car-listings/bmw/x5/2016/black/x5_1.jpg",
      "image2": "src/assets/car-listings/bmw/x5/2016/black/x5_2.jpg",
      "image3": "src/assets/car-listings/bmw/x5/2016/black/x5_3.jpg",
      "image4": "src/assets/car-listings/bmw/x5/2016/black/x5_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100008"
  },

  {
    "id": 9,
    "type": "Car",
    "make": "Skoda",
    "model": "Octavia VRS",
    "colour": "Metallic Lime Green",
    "engine": 2.0,
    "engineType": "Diesel",
    "mileage": 8991,
    "transmission": "Manual",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": true,
                  "heatedSeats": true,
                  "heatedWindscreen": true,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2018,
    "serviceHistory": "Full (Dealer)",
    "price": 20299,
    "images": {
      "image1": "src/assets/car-listings/skoda/octavia/2018/green/octavia_1.jpg",
      "image2": "src/assets/car-listings/skoda/octavia/2018/green/octavia_2.jpg",
      "image3": "src/assets/car-listings/skoda/octavia/2018/green/octavia_3.jpg",
      "image4": "src/assets/car-listings/skoda/octavia/2018/green/octavia_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100009"
  },

  {
    "id": 10,
    "type": "Car",
    "make": "Renault",
    "model": "Megane",
    "colour": "Metallic Red",
    "engine": 1.5,
    "engineType": "Diesel",
    "mileage": 28404,
    "transmission": "Manual",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": false,
                  "heatedSeats": false,
                  "heatedWindscreen": false,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": false,
                  "GPS": true
                },
    "year": 2014,
    "serviceHistory": "Full (Dealer)",
    "price": 6749,
    "images": {
      "image1": "src/assets/car-listings/renault/megane/2014/red/megane_1.jpg",
      "image2": "src/assets/car-listings/renault/megane/2014/red/megane_2.jpg",
      "image3": "src/assets/car-listings/renault/megane/2014/red/megane_3.jpg",
      "image4": "src/assets/car-listings/renault/megane/2014/red/megane_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100010"
  },

  {
    "id": 11,
    "type": "Car",
    "make": "Vauxhall",
    "model": "Astra GTC",
    "colour": "Yellow",
    "engine": 2.0,
    "engineType": "Petrol",
    "mileage": 20100,
    "transmission": "Manual",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": false,
                  "heatedSeats": true,
                  "heatedWindscreen": true,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2015,
    "serviceHistory": "Full (Dealer)",
    "price": 11755,
    "images": {
      "image1": "src/assets/car-listings/vauxhall/astra gtc/2015/yellow/astra_gtc_1.jpg",
      "image2": "src/assets/car-listings/vauxhall/astra gtc/2015/yellow/astra_gtc_2.jpg",
      "image3": "src/assets/car-listings/vauxhall/astra gtc/2015/yellow/astra_gtc_3.jpg",
      "image4": "src/assets/car-listings/vauxhall/astra gtc/2015/yellow/astra_gtc_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100011"
  },

  {
    "id": 12,
    "type": "Car",
    "make": "Land Rover",
    "model": "Range Rover",
    "colour": "Silver",
    "engine": 3.6,
    "engineType": "Diesel",
    "mileage": 72884,
    "transmission": "Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": true,
                  "heatedSeats": true,
                  "heatedWindscreen": true,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2008,
    "serviceHistory": "Full (Dealer)",
    "price": 10999,
    "images": {
      "image1": "src/assets/car-listings/range rover/vogue/2008/silver/vogue_1.jpg",
      "image2": "src/assets/car-listings/range rover/vogue/2008/silver/vogue_2.jpg",
      "image3": "src/assets/car-listings/range rover/vogue/2008/silver/vogue_3.jpg",
      "image4": "src/assets/car-listings/range rover/vogue/2008/silver/vogue_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100012"
  },

  {
    "id": 13,
    "type": "Car",
    "make": "Audi",
    "model": "A3",
    "colour": "Black",
    "engine": 1.4,
    "engineType": "Petrol",
    "mileage": 14524,
    "transmission": "Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": false,
                  "heatedSeats": false,
                  "heatedWindscreen": false,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": false,
                  "GPS": false
                },
    "year": 2017,
    "serviceHistory": "Full (Dealer)",
    "price": 18495,
    "images": {
      "image1": "src/assets/car-listings/audi/a3/2017/black/a3_1.jpg",
      "image2": "src/assets/car-listings/audi/a3/2017/black/a3_2.jpg",
      "image3": "src/assets/car-listings/audi/a3/2017/black/a3_3.jpg",
      "image4": "src/assets/car-listings/audi/a3/2017/black/a3_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100013"
  },

  {
    "id": 14,
    "type": "Car",
    "make": "Audi",
    "model": "Q7",
    "colour": "Blue",
    "engine": 3.0,
    "engineType": "Diesel",
    "mileage": 9921,
    "transmission": "Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": true,
                  "heatedSeats": true,
                  "heatedWindscreen": true,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2019,
    "serviceHistory": "Full (Dealer)",
    "price": 63299,
    "images": {
      "image1": "src/assets/car-listings/audi/q7/2019/blue/q7_1.jpg",
      "image2": "src/assets/car-listings/audi/q7/2019/blue/q7_2.jpg",
      "image3": "src/assets/car-listings/audi/q7/2019/blue/q7_3.jpg",
      "image4": "src/assets/car-listings/audi/q7/2019/blue/q7_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100014"
  },

  {
    "id": 15,
    "type": "Car",
    "make": "Audi",
    "model": "A4",
    "colour": "Gun Metal Grey",
    "engine": 1.8,
    "engineType": "Petrol",
    "mileage": 34201,
    "transmission": "Manual",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": true,
                  "heatedSeats": true,
                  "heatedWindscreen": false,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": false,
                  "GPS": true
                },
    "year": 2014,
    "serviceHistory": "Full",
    "price": 12595,
    "images": {
      "image1": "src/assets/car-listings/audi/a4/2014/grey/a4_1.jpg",
      "image2": "src/assets/car-listings/audi/a4/2014/grey/a4_2.jpg",
      "image3": "src/assets/car-listings/audi/a4/2014/grey/a4_3.jpg",
      "image4": "src/assets/car-listings/audi/a4/2014/grey/a4_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100015"
  },

  {
    "id": 16,
    "type": "Car",
    "make": "Audi",
    "model": "RS6",
    "colour": "Black",
    "engine": 4.0,
    "engineType": "Petrol",
    "mileage": 20596,
    "transmission": "Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": true,
                  "heatedSeats": true,
                  "heatedWindscreen": true,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2018,
    "serviceHistory": "Full (Dealer)",
    "price": 67999,
    "images": {
      "image1": "src/assets/car-listings/audi/rs6/2018/black/rs6_1.jpg",
      "image2": "src/assets/car-listings/audi/rs6/2018/black/rs6_2.jpg",
      "image3": "src/assets/car-listings/audi/rs6/2018/black/rs6_3.jpg",
      "image4": "src/assets/car-listings/audi/rs6/2018/black/rs6_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100016"
  },

  {
    "id": 17,
    "type": "Car",
    "make": "Skoda",
    "model": "Fabia",
    "colour": "Candy White",
    "engine": 1.2,
    "engineType": "Petrol",
    "mileage": 23166,
    "transmission": "Manual",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": false,
                  "heatedSeats": true,
                  "heatedWindscreen": false,
                  "PAS": true,
                  "parkingSensors": false,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2016,
    "serviceHistory": "Part (Dealer)",
    "price": 8950,
    "images": {
      "image1": "src/assets/car-listings/skoda/fabia/2016/white/fabia_1.jpg",
      "image2": "src/assets/car-listings/skoda/fabia/2016/white/fabia_2.jpg",
      "image3": "src/assets/car-listings/skoda/fabia/2016/white/fabia_3.jpg",
      "image4": "src/assets/car-listings/skoda/fabia/2016/white/fabia_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100017"
  },

  {
    "id": 18,
    "type": "Car",
    "make": "BMW",
    "model": "530d",
    "colour": "Champagne Quartz",
    "engine": 3.0,
    "engineType": "Diesel",
    "mileage": 3311,
    "transmission": "Semi-Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": true,
                  "heatedSeats": true,
                  "heatedWindscreen": true,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2018,
    "serviceHistory": "Full (Dealer)",
    "price": 41975,
    "images": {
      "image1": "src/assets/car-listings/bmw/5-series/530d/2018/champagne/530d_1.jpg",
      "image2": "src/assets/car-listings/bmw/5-series/530d/2018/champagne/530d_2.jpg",
      "image3": "src/assets/car-listings/bmw/5-series/530d/2018/champagne/530d_3.jpg",
      "image4": "src/assets/car-listings/bmw/5-series/530d/2018/champagne/530d_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100018"
  },

  {
    "id": 19,
    "type": "Car",
    "make": "Mini",
    "model": "Clubman",
    "colour": "Red",
    "engine": 2.0,
    "engineType": "Petrol",
    "mileage": 18212,
    "transmission": "Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": false,
                  "heatedSeats": false,
                  "heatedWindscreen": false,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": false,
                  "GPS": true
                },
    "year": 2016,
    "serviceHistory": "Full (Dealer)",
    "price": 16490,
    "images": {
      "image1": "src/assets/car-listings/mini/2016/red/clubman_1.jpg",
      "image2": "src/assets/car-listings/mini/2016/red/clubman_2.jpg",
      "image3": "src/assets/car-listings/mini/2016/red/clubman_3.jpg",
      "image4": "src/assets/car-listings/mini/2016/red/clubman_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100019"
  },

  {
    "id": 20,
    "type": "Car",
    "make": "Citroen",
    "model": "DS4",
    "colour": "Black",
    "engine": 2.0,
    "engineType": "Diesel",
    "mileage": 24612,
    "transmission": "Manual",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": true,
                  "heatedSeats": true,
                  "heatedWindscreen": false,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": false,
                  "GPS": true
                },
    "year": 2016,
    "serviceHistory": "Part (Dealer)",
    "price": 9270,
    "images": {
      "image1": "src/assets/car-listings/citroen/ds4/2016/black/ds4_1.jpg",
      "image2": "src/assets/car-listings/citroen/ds4/2016/black/ds4_2.jpg",
      "image3": "src/assets/car-listings/citroen/ds4/2016/black/ds4_3.jpg",
      "image4": "src/assets/car-listings/citroen/ds4/2016/black/ds4_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100020"
  },

  {
    "id": 21,
    "type": "Car",
    "make": "Jaguar",
    "model": "F-Pace",
    "colour": "Black",
    "engine": 2.0,
    "engineType": "Diesel",
    "mileage": 20117,
    "transmission": "Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": true,
                  "heatedSeats": true,
                  "heatedWindscreen": true,
                  "PAS": true,
                  "parkingSensors": false,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2016,
    "serviceHistory": "Full (Dealer)",
    "price": 30082,
    "images": {
      "image1": "src/assets/car-listings/jaguar/f-pace/2016/black/f-pace_1.jpg",
      "image2": "src/assets/car-listings/jaguar/f-pace/2016/black/f-pace_2.jpg",
      "image3": "src/assets/car-listings/jaguar/f-pace/2016/black/f-pace_3.jpg",
      "image4": "src/assets/car-listings/jaguar/f-pace/2016/black/f-pace_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100021"
  },

  {
    "id": 22,
    "type": "Car",
    "make": "Ford",
    "model": "Ranger (Wildtrack)",
    "colour": "Orange",
    "engine": 3.2,
    "engineType": "Diesel",
    "mileage": 26209,
    "transmission": "Manual",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": false,
                  "heatedSeats": false,
                  "heatedWindscreen": true,
                  "PAS": true,
                  "parkingSensors": false,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2016,
    "serviceHistory": "Full (Dealer)",
    "price": 23950,
    "images": {
      "image1": "src/assets/car-listings/ford/ranger/wildtrack/2016/orange/ranger_wildtrack_1.jpg",
      "image2": "src/assets/car-listings/ford/ranger/wildtrack/2016/orange/ranger_wildtrack_2.jpg",
      "image3": "src/assets/car-listings/ford/ranger/wildtrack/2016/orange/ranger_wildtrack_3.jpg",
      "image4": "src/assets/car-listings/ford/ranger/wildtrack/2016/orange/ranger_wildtrack_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100022"
  },

  {
    "id": 23,
    "type": "Car",
    "make": "Mercedes",
    "model": "C220d AMG",
    "colour": "Metallic Red",
    "engine": 2.0,
    "engineType": "Diesel",
    "mileage": 2635,
    "transmission": "Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": true,
                  "heatedSeats": false,
                  "heatedWindscreen": true,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2019,
    "serviceHistory": "Full (Dealer)",
    "price": 37999,
    "images": {
      "image1": "src/assets/car-listings/mercedes/c-class/c220d/2019/red/c220d_1.jpg",
      "image2": "src/assets/car-listings/mercedes/c-class/c220d/2019/red/c220d_2.jpg",
      "image3": "src/assets/car-listings/mercedes/c-class/c220d/2019/red/c220d_3.jpg",
      "image4": "src/assets/car-listings/mercedes/c-class/c220d/2019/red/c220d_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100023"
  },

  {
    "id": 24,
    "type": "Car",
    "make": "Mercedes",
    "model": "C63 AMG",
    "colour": "Iridium Metallic Silver",
    "engine": 4.0,
    "engineType": "Petrol",
    "mileage": 2101,
    "transmission": "Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": true,
                  "heatedSeats": true,
                  "heatedWindscreen": true,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2019,
    "serviceHistory": "Full (Dealer)",
    "price": 59970,
    "images": {
      "image1": "src/assets/car-listings/mercedes/c-class/c63/2019/silver/c63_1.jpg",
      "image2": "src/assets/car-listings/mercedes/c-class/c63/2019/silver/c63_2.jpg",
      "image3": "src/assets/car-listings/mercedes/c-class/c63/2019/silver/c63_3.jpg",
      "image4": "src/assets/car-listings/mercedes/c-class/c63/2019/silver/c63_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100024"
  },

  {
    "id": 25,
    "type": "Car",
    "make": "Nissan",
    "model": "Qashqai",
    "colour": "Purple",
    "engine": 1.5,
    "engineType": "Diesel",
    "mileage": 42141,
    "transmission": "Manual",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": false,
                  "heatedSeats": false,
                  "heatedWindscreen": false,
                  "PAS": true,
                  "parkingSensors": false,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2014,
    "serviceHistory": "Full",
    "price": 8666,
    "images": {
      "image1": "src/assets/car-listings/nissan/qashqai/2014/purple/qashqai_1.jpg",
      "image2": "src/assets/car-listings/nissan/qashqai/2014/purple/qashqai_2.jpg",
      "image3": "src/assets/car-listings/nissan/qashqai/2014/purple/qashqai_3.jpg",
      "image4": "src/assets/car-listings/nissan/qashqai/2014/purple/qashqai_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100025"
  },

  {
    "id": 26,
    "type": "Car",
    "make": "Nissan",
    "model": "GT-R",
    "colour": "Lime",
    "engine": 3.8,
    "engineType": "Petrol",
    "mileage": 54197,
    "transmission": "Semi-Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": false,
                  "heatedSeats": false,
                  "heatedWindscreen": false,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": false,
                  "GPS": true
                },
    "year": 2010,
    "serviceHistory": "Full (Dealer)",
    "price": 35699,
    "images": {
      "image1": "src/assets/car-listings/nissan/gtr/2010/lime/gtr_1.jpg",
      "image2": "src/assets/car-listings/nissan/gtr/2010/lime/gtr_2.jpg",
      "image3": "src/assets/car-listings/nissan/gtr/2010/lime/gtr_3.jpg",
      "image4": "src/assets/car-listings/nissan/gtr/2010/lime/gtr_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100026"
  },

  {
    "id": 27,
    "type": "Car",
    "make": "Porsche",
    "model": "911",
    "colour": "Black",
    "engine": 3.0,
    "engineType": "Petrol",
    "mileage": 2270,
    "transmission": "Manual",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": true,
                  "heatedSeats": true,
                  "heatedWindscreen": true,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2019,
    "serviceHistory": "Full (Dealer)",
    "price": 118095,
    "images": {
      "image1": "src/assets/car-listings/porsche/911/2019/black/911_1.jpg",
      "image2": "src/assets/car-listings/porsche/911/2019/black/911_2.jpg",
      "image3": "src/assets/car-listings/porsche/911/2019/black/911_3.jpg",
      "image4": "src/assets/car-listings/porsche/911/2019/black/911_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100027"
  },

  {
    "id": 28,
    "type": "Car",
    "make": "Honda",
    "model": "Civic Type R",
    "colour": "White",
    "engine": 2.0,
    "engineType": "Petrol",
    "mileage": 65200,
    "transmission": "Manual",
    "modCons": {
                  "airCon": true,
                  "cdMp3": false,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": false,
                  "heatedSeats": false,
                  "heatedWindscreen": false,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": false,
                  "GPS": false
                },
    "year": 2008,
    "serviceHistory": "Part (Dealer)",
    "price": 6295,
    "images": {
      "image1": "src/assets/car-listings/honda/civic/2008/white/civic_1.jpg",
      "image2": "src/assets/car-listings/honda/civic/2008/white/civic_2.jpg",
      "image3": "src/assets/car-listings/honda/civic/2008/white/civic_3.jpg",
      "image4": "src/assets/car-listings/honda/civic/2008/white/civic_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100028"
  },

  {
    "id": 29,
    "type": "Car",
    "make": "Lexus",
    "model": "CT200H",
    "colour": "Black",
    "engine": 1.8,
    "engineType": "Hybrid",
    "mileage": 55196,
    "transmission": "Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": false,
                  "heatedSeats": false,
                  "heatedWindscreen": false,
                  "PAS": true,
                  "parkingSensors": false,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2014,
    "serviceHistory": "Full",
    "price": 11999,
    "images": {
      "image1": "src/assets/car-listings/lexus/ct200h/2014/black/ct200h_1.jpg",
      "image2": "src/assets/car-listings/lexus/ct200h/2014/black/ct200h_2.jpg",
      "image3": "src/assets/car-listings/lexus/ct200h/2014/black/ct200h_3.jpg",
      "image4": "src/assets/car-listings/lexus/ct200h/2014/black/ct200h_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100029"
  },

  {
    "id": 30,
    "type": "Car",
    "make": "Renault",
    "model": "Zoe",
    "colour": "Black",
    "engine": 0,
    "engineType": "Electric",
    "mileage": 37196,
    "transmission": "Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": false,
                  "heatedSeats": false,
                  "heatedWindscreen": false,
                  "PAS": true,
                  "parkingSensors": false,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2015,
    "serviceHistory": "Full (Dealer)",
    "price": 8129,
    "images": {
      "image1": "src/assets/car-listings/renault/zoe/2015/black/zoe_1.jpg",
      "image2": "src/assets/car-listings/renault/zoe/2015/black/zoe_2.jpg",
      "image3": "src/assets/car-listings/renault/zoe/2015/black/zoe_3.jpg",
      "image4": "src/assets/car-listings/renault/zoe/2015/black/zoe_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100030"
  },

  {
    "id": 31,
    "type": "Car",
    "make": "BMW",
    "model": "318d",
    "colour": "White",
    "engine": 1.8,
    "engineType": "Diesel",
    "mileage": 41602,
    "transmission": "Semi-Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": false,
                  "heatedSeats": false,
                  "heatedWindscreen": false,
                  "PAS": true,
                  "parkingSensors": false,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2015,
    "serviceHistory": "Full (Dealer)",
    "price": 13998,
    "images": {
      "image1": "src/assets/car-listings/bmw/3-series/318d/2018/white/318d_1.jpg",
      "image2": "src/assets/car-listings/bmw/3-series/318d/2018/white/318d_2.jpg",
      "image3": "src/assets/car-listings/bmw/3-series/318d/2018/white/318d_3.jpg",
      "image4": "src/assets/car-listings/bmw/3-series/318d/2018/white/318d_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100031"
  },

  {
    "id": 32,
    "type": "Car",
    "make": "Alfa Romeo",
    "model": "Giulia",
    "colour": "Black",
    "engine": 2.0,
    "engineType": "Petrol",
    "mileage": 3206,
    "transmission": "Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": true,
                  "heatedSeats": true,
                  "heatedWindscreen": true,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2019,
    "serviceHistory": "Full (Dealer)",
    "price": 30495,
    "images": {
      "image1": "src/assets/car-listings/alfa romeo/giulia/2019/black/giulia_1.jpg",
      "image2": "src/assets/car-listings/alfa romeo/giulia/2019/black/giulia_2.jpg",
      "image3": "src/assets/car-listings/alfa romeo/giulia/2019/black/giulia_3.jpg",
      "image4": "src/assets/car-listings/alfa romeo/giulia/2019/black/giulia_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100032"
  },

  {
    "id": 33,
    "type": "Car",
    "make": "Mercedes",
    "model": "CL63 AMG",
    "colour": "Black",
    "engine": 5.5,
    "engineType": "Petrol",
    "mileage": 32635,
    "transmission": "Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": true,
                  "heatedSeats": true,
                  "heatedWindscreen": true,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2013,
    "serviceHistory": "Full (Dealer)",
    "price": 30995,
    "images": {
      "image1": "src/assets/car-listings/mercedes/cl-series/cl63/2013/black/cl63_1.jpg",
      "image2": "src/assets/car-listings/mercedes/cl-series/cl63/2013/black/cl63_2.jpg",
      "image3": "src/assets/car-listings/mercedes/cl-series/cl63/2013/black/cl63_3.jpg",
      "image4": "src/assets/car-listings/mercedes/cl-series/cl63/2013/black/cl63_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100033"
  },

  {
    "id": 34,
    "type": "Car",
    "make": "Mercedes",
    "model": "CLS350d",
    "colour": "White",
    "engine": 3.0,
    "engineType": "Diesel",
    "mileage": 42341,
    "transmission": "Auto",
    "modCons": {
                  "airCon": true,
                  "cdMp3": true,
                  "cruise": true,
                  "electricWindows": true, 
                  "electricMirrors": true,
                  "heatedMirrors": true,
                  "heatedSeats": true,
                  "heatedWindscreen": true,
                  "PAS": true,
                  "parkingSensors": true,
                  "reverseCameraAssist": true,
                  "GPS": true
                },
    "year": 2013,
    "serviceHistory": "Full",
    "price": 20875,
    "images": {
      "image1": "src/assets/car-listings/mercedes/cls-series/cls350d/2015/white/cls350d_1.jpg",
      "image2": "src/assets/car-listings/mercedes/cls-series/cls350d/2015/white/cls350d_2.jpg",
      "image3": "src/assets/car-listings/mercedes/cls-series/cls350d/2015/white/cls350d_3.jpg",
      "image4": "src/assets/car-listings/mercedes/cls-series/cls350d/2015/white/cls350d_4.jpg",
      "image5": null,
      "image6": null,
      "image7": null,
      "image8": null,
      "image9": null,
      "image10": null
    },
    "refNo": "EM-100034"
  }
]

export {carData};
